name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16' # Specify your Node.js version
        cache: 'npm'

    - run: npm ci

    # Prevent warnings from breaking the build
    - name: Build the project
      run: CI=false npm run build

    - name: Run tests
      run: npm test
