name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  AZURE_WEBAPP_NAME: AmirRecipeWeb
  AZURE_WEBAPP_PACKAGE_PATH: "./build" # Adjust the path if your build output is elsewhere

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v4

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16' # Specify the Node.js version required
        cache: 'npm'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Build the project
    - name: Build the project
      run: CI=false npm run build

    # Step 5: Run tests
    - name: Run tests
      run: npm test

    # Step 6: Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
